### ISSUE TITLE
POSIX standard link now available?

### ISSUE THREAD

**Issue by dezman** [shuveb/loti#6]
There is this blog here https://unixism.net/2020/07/getting-a-pdf-version-of-the-posix-standard-document/, I think the doc may have been made slightly easier to access in this location https://publications.opengroup.org/g101.

**Comment by shuveb** [comment]
That link, as the description says "... provides complete information on what's new in the Single UNIX Specification, Version 4, including POSIX 1003.1" and is only 436 pages. The specification is 3,952 pages. While the HTML version is more easily accessible, the PDF version is a pain to find and downloading that is what the article describes.
